<?php

/**
* This file has an array of possible author names
*
* If there is only one author with a last name, then the format is
*  lastname => Full Name,
* If there are multiple authors with the same last name, then the format is
*  lastname => array(
*   0 => Full Name, 0_start => Start Year, 0_end => End Year,
*   1 => Full Name, 1_start => Start Year, 1_end => End Year),
*/

$authorByName = array( 
"wilson" => "James Wilson",
"jay" => "John Jay",
"cushing" => "William Cushing",
"blair" => "John Blair, Jr.",
"iredell" => "James Iredell",
"johnson" => array(
	"0" => "Thomas Johnson", "0_start" => 1792, "0_end" => 1793,
	"1" => "William Johnson", "1_start" => 1804, "1_end" => 1834),
"paterson" => "William Paterson",
"chase" => array(
	"0" => "Samuel Chase",
	"1" => "Salmon P. Chase"),
"ellsworth" => "Oliver Ellsworth",
"washington" => "Bushrod Washington",
"moore" => "Alfred Moore",
"marshall" => array(
	"0" => "John Marshall", "0_start" => 1801, "0_end" => 1835,
	"1" => "Thurgood Marshall", "1_start" => 1967, "1_end" => 1991),
"livingston" => "Henry Brockholst Livingston",	
"todd" => "Thomas Todd",
"duvall" => "Gabriel Duvall",
"story" => "Joseph Story",
"thompson" => "Smith Thompson",
"trimble" => "Robert Trimble",
"mclean" => "John McLean",
"baldwin" => "Henry Baldwin",
"wayne" => "James Moore Wayne",
"taney" => "Roger B. Taney",
"barbour" => "Philip Pendleton Barbour",
"catron" => "John Catron",
"mckinley" => "John McKinley",
"daniel" => "Peter Vivian Daniel",
"nelson" => "Samuel Nelson",
"woodbury" => "Levi Woodbury",
"grier" => "Robert Cooper Grier",
"curtis" => "Benjamin Robbins Curtis",
"campbell" => "John Archibald Campbell", 
"clifford" => "Nathan Clifford",
"swayne" => "Noah Haynes Swayne",
"miller" => "Samuel Freeman Miller",
"davis" => "David Davis",
"field" => "Stephen Johnson Field",
"strong" => "William Strong",
"bradley" => "Joseph P. Bradley",
"hunt" => "Ward Hunt",
"waite" => "Morrison Waite",
"harlan" => array(
	"0" => "John Marshall Harlan", "0_start" => 1877, "0_end" => 1911,
	"1" => "John Marshall Harlan II", "1_start" => 1955, "1_end" => 1971),
"woods" => "William Burnham Woods",
"matthews" => "Stanley Matthews",
"gray" => "Horace Gray",
"blatchford" => "Samuel Blatchford",
"lamar" => array(
	"0" =>"Lucius Quintus Cincinnatus Lamar", "0_start" => 1888, "0_end" => 1893,
	"1" => "Joseph Rucker Lamar", "1_start" => 1911, "1_end" => 1916),
"fuller" => "Melville Fuller",
"fullter" => "Melville Fuller", //I found this mispelling if Justice Fuller's name on OpenJurist in 153 US 614
"brewer" => "David Josiah Brewer",
"brown" => "Henry Billings Brown",
"shiras" => "George Shiras, Jr.",
"jackson" => array(
	"0" => "Howell Edmunds Jackson", "0_start" => 1893, "0_end" => 1895,
	"1" => "Robert H. Jackson",  "1_start" => 1941, "1_end" => 1954),
"peckham" => "Rufus Wheeler Peckham",
"mckenna" => "Joseph McKenna",
"holmes" => "Oliver Wendell Holmes, Jr.",
"day" => "William R. Day",
"moody" => "William Henry Moody",
"lurton" => "Horace Harmon Lurton",
"hughes" => "Charles Evans Hughes",
"devanter" => "Willis Van Devanter",
"pitney" => "Mahlon Pitney",
"mcreynolds" => "James Clark McReynolds",
"brandeis" => "Louis Brandeis",
"clarke" => "John Hessin Clarke",
"taft" => "William Howard Taft",
"sutherland" => "George Sutherland",
"butler" => "Pierce Butler",
"sanford" => "Edward Terry Sanford",
"stone" => "Harlan F. Stone",
"hughes" => "Charles Evans Hughes",
"roberts" => "Owen Roberts",
"cardozo" => "Benjamin N. Cardozo",
"black" => "Hugo Black",
"reed" => "Stanley Forman Reed",
"frankfurter" => "Felix Frankfurter",
"douglas" => "William O. Douglas",
"murphy" => "Frank Murphy",
"byrnes" => "James F. Byrnes",
"rutledge" => array(
	"0" => "Wiley Blount Rutledge", "0_start" => 1943, "0_end" => 1949,
	"1" => "John Rutledge", "1_start" => 1790, "1_end" => 1795),
"burton" => "Harold Hitz Burton",
"vinson" => "Fred M. Vinson",
"clark" => "Tom C. Clark",
"minton" => "Sherman Minton",
"warren" => "Earl Warren",
"brennan" => "William J. Brennan, Jr.",
"whittaker" => "Charles Evans Whittaker",
"stewart" => "Potter Stewart",
"white" => array(
	"0" => "Byron White", "0_start" => 1962, "0_end" => 1993,
	"1" => "Edward Douglass White", "1_start" => 1894, "1_end" => 1921),
"goldberg" => "Arthur Goldberg",
"fortas" => "Abe Fortas",
"burger" => "Warren E. Burger",
"blackmun" => "Harry Blackmun",
"powell" => "Lewis F. Powell, Jr.",
"rehnquist" => "William Rehnquist",
"stevens" => "John Paul Stevens",
"o'connor" => "Sandra Day O'Connor",
"scalia" => "Antonin Scalia",
"kennedy" => "Anthony Kennedy",
"souter" => "David Hackett Souter",
"thomas" => "Clarence Thomas",
"ginsburg" => "Ruth Bader Ginsburg",
"breyer" => "Stephen Breyer",
"roberts" => "John G. Roberts",
"alito" => "Samuel Alito",
"sotomayor" => "Sonia Sotomayor");
?>